### ISSUE TITLE
Doesn't work with webpack-blocks@1.0.0-rc

### ISSUE THREAD

**Issue by serhii-shvaher** [diegohaz/webpack-blocks-split-vendor#22]
Requires peerDependency `@webpack-blocks/webpack2` which is not part of webpack-blocks anymore.

**Comment by diegohaz** [comment]
Yeah, we still need to update it to webpack-blocks v1 API.

PR is welcome.

**Comment by serhii-shvaher** [comment]
@diegohaz ok, I'll try to do PR.
