### ISSUE TITLE
Remove extension checking

### ISSUE THREAD

**Issue by dmitmel** [diegohaz/webpack-blocks-split-vendor#24]
Function `isVendor` returns `true` when the provided module:
1. is in the `node_modules` directory
2. **has `.js` extension**
3. hasn't been excluded

### Problem
The 2nd condition doesn't allow modules with other file extensions (`.jsx`, `.ts`, `.css` etc) to be extracted.

### Possible solution
Instead of hard-coding regexp for checking file extension, you can pass it to the block using an option (e. g. `test`).

**Comment by diegohaz** [comment]
Thank you for reporting. Would you like to open a PR?

**Comment by dmitmel** [comment]
Sure. I've already forked your repo.

**Comment by diegohaz** [comment]
Closed in #25
